name:                "generative-design"
version:             "0.1.0.0"
git:                 "git@github.com:cyberglot/generative-design.git"
license:             "Contributor Covenant v2.0"
author:              "April Gonçalves"
maintainer:          "april@cyberglot.me"
copyright:           "2020 cyberglot.space"
synopsis:            "Generate good compositions for your artwork"
description:         "Generate good compositions for your artwork"

extra-source-files:
- README.md

ghc-options:
  - -O2
  - -flate-specialise
  - -fspecialise-aggressively
  - -fplugin=Polysemy.Plugin
  - -Wall
  - -Wcompat
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns

default-extensions:
  - DataKinds
  - FlexibleContexts
  - GADTs
  - LambdaCase
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - TemplateHaskell

  - GeneralizedNewtypeDeriving
  - DeriveGeneric

  - OverloadedStrings
  - LambdaCase

dependencies:
  - base >= 4.7 && < 5

  - polysemy >= 1.2.1.0 && < 1.3
  - polysemy-plugin >= 0.2.3.0 && < 0.3
  - polysemy-zoo >= 0.6.0.1 && < 0.7
  - polysemy-RandomFu
  - cairo
  - diagrams-cairo
  - diagrams
  - algebraic-graphs

library:
  source-dirs: src

executables:
  generative-design-exe:
    main:         Main.hs
    source-dirs:  app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generative-design

tests:
  generative-design-test:
    main:        Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - generative-design
